---
title: Title
author: Jeppe Fjeldgaard
output: pdf_document
fontsize: 11pt
geometry: "left=6cm, right=5cm, top=2.5cm, bottom=2.5cm"
toc: true

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
# Abstract {-}

An abstract

# Introduction

Intro text here ...

# Asking the right question

# Data 

```{r data, message=FALSE, warning=FALSE}

# Read raw data
rawdataurl <- "https://github.com/JeppeFjeldgaard/Segregation/blob/master/Data/Elevtal.csv?raw=true"
df <- readr::read_csv2(url(rawdataurl), skip = 7) 

# Clean data
df <- 
df %>% 
  dplyr::filter(!is.na(Kommunenummer)) %>% 
  dplyr::select(-Herkomst) %>% 
  dplyr::rename(Origin = `Vestlig - Ikke-Vestlig`, 
                `Municipal` = Kommunenummer,
                `School` = Institutionsnummer)

# Make table
df %>% 
  dplyr::select(`School`, `Municipal`, Origin, "2008/2009":"2018/2019") %>% 
  dplyr::group_by(`School`, `Municipal`, Origin) %>% 
  dplyr::summarize_at(vars("2008/2009":"2018/2019"), sum, na.rm = TRUE) %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", 
                                                  "hover", 
                                                  font_size = 11))
```

# Mapping

```{r spatial data, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}

# Download data
download.file("https://github.com/JeppeFjeldgaard/Segregation/blob/master/Data/ADM.zip?raw=true", destfile = "ADM.zip" , mode='wb')
unzip("ADM.zip", exdir = ".")
file.remove("ADM.zip")

# Read shapefile
shape.sf <- sf::st_read("./ADM", "KOMMUNE") 

# Dissolve polygons
shape.sf <-
  shape.sf %>% 
  dplyr::mutate(area = sf::st_area(shape.sf),
                Municipal = as.character(as.numeric(as.character(KOMKODE)))) %>% 
  dplyr::group_by(Municipal) %>% 
  dplyr::summarise(area = sum(area)) 

```





